package wafscan_test

import (
	"context"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
	"time"

	"github.com/DonatoReis/blackhorn-modules/modules/wafscan"
	"github.com/DonatoReis/blackhorn-modules/pkg/module"
)

// ─── Helpers ──────────────────────────────────────────────────────────────────

// isAttackProbe checks if a request is the WAF attack probe (any suspicious query param).
func isAttackProbe(r *http.Request) bool {
	raw := r.URL.RawQuery
	return strings.Contains(raw, "id=") && strings.Contains(raw, "OR") ||
		strings.Contains(raw, "script") || strings.Contains(raw, "etc") ||
		strings.Contains(raw, "1%27") || strings.Contains(raw, "%27")
}

// cloudflareServer simulates a Cloudflare-protected origin.
func cloudflareServer(t *testing.T) *httptest.Server {
	t.Helper()
	return httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("server", "cloudflare")
		w.Header().Set("cf-ray", "7abc123456789-GRU")
		if isAttackProbe(r) {
			w.WriteHeader(403)
			w.Write([]byte(`cloudflare ray id: 7abc123456789-GRU attention required! | cloudflare`))
			return
		}
		w.WriteHeader(200)
		w.Write([]byte(`{"status":"ok"}`))
	}))
}

// modsecurityServer simulates a ModSecurity-blocked response.
func modsecurityServer(t *testing.T) *httptest.Server {
	t.Helper()
	return httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if isAttackProbe(r) {
			w.Header().Set("server", "Apache/2.4 mod_security")
			w.WriteHeader(406)
			w.Write([]byte(`Not Acceptable. This error was generated by mod_security`))
			return
		}
		w.WriteHeader(200)
		w.Write([]byte(`OK`))
	}))
}

// incapsulaServer simulates an Imperva/Incapsula WAF.
func incapsulaServer(t *testing.T) *httptest.Server {
	t.Helper()
	return httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("x-iinfo", "11-123456-0 NNNN CT(52,0,0,0) RT(1638000000000,0) q(0,0,0,-1) r(0,-1) U5")
		http.SetCookie(w, &http.Cookie{Name: "incap_ses_123_456", Value: "testvalue"})
		w.WriteHeader(403)
		w.Write([]byte(`incapsula incident id: 1234567890`))
	}))
}

// f5BigIPServer simulates F5 BIG-IP ASM WAF.
func f5BigIPServer(t *testing.T) *httptest.Server {
	t.Helper()
	return httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(403)
		w.Write([]byte(`The requested URL was rejected. Please consult with your administrator. Your support ID is: 12345678901234567890`))
	}))
}

// genericBlockServer: returns 200 for clean, 403 for attack.
func genericBlockServer(t *testing.T) *httptest.Server {
	t.Helper()
	return httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if isAttackProbe(r) {
			w.WriteHeader(403)
			w.Write([]byte(`Forbidden`))
			return
		}
		w.WriteHeader(200)
		w.Write([]byte(`OK`))
	}))
}

// noWAFServer: always returns 200 for any request.
func noWAFServer(t *testing.T) *httptest.Server {
	t.Helper()
	return httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(200)
		w.Write([]byte(`<html><body>Welcome</body></html>`))
	}))
}

// customSigServer: returns specific header for custom signature testing.
func customSigServer(t *testing.T, headerKey, headerValue string) *httptest.Server {
	t.Helper()
	return httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set(headerKey, headerValue)
		w.WriteHeader(200)
		w.Write([]byte(`OK`))
	}))
}

func clientFor(srv *httptest.Server) *http.Client { return srv.Client() }

// ─── Tests ────────────────────────────────────────────────────────────────────

func TestName(t *testing.T) {
	m := wafscan.New()
	if m.Name() != "wafscan" {
		t.Fatalf("expected 'wafscan', got %q", m.Name())
	}
}

func TestModuleImplementsInterface(t *testing.T) {
	var _ module.Module = wafscan.New()
}

// TestCloudflareDetected: Cloudflare WAF detected via headers.
func TestCloudflareDetected(t *testing.T) {
	srv := cloudflareServer(t)
	defer srv.Close()

	m := wafscan.NewWithClient(clientFor(srv))
	findings, err := m.Run(context.Background(), module.Input{
		Target: srv.URL + "/",
	})
	if err != nil {
		t.Fatalf("Run failed: %v", err)
	}
	found := false
	for _, f := range findings {
		if strings.Contains(f.Extra["waf_name"], "Cloudflare") {
			found = true
		}
	}
	if !found {
		t.Errorf("expected Cloudflare WAF detection, got: %v", findings)
	}
}

// TestModSecurityDetected: ModSecurity detected via body pattern.
func TestModSecurityDetected(t *testing.T) {
	srv := modsecurityServer(t)
	defer srv.Close()

	m := wafscan.NewWithClient(clientFor(srv))
	findings, err := m.Run(context.Background(), module.Input{
		Target: srv.URL + "/",
	})
	if err != nil {
		t.Fatalf("Run failed: %v", err)
	}
	found := false
	for _, f := range findings {
		if strings.Contains(f.Extra["waf_name"], "ModSecurity") || strings.Contains(f.Extra["waf_name"], "generic") {
			found = true
		}
	}
	if !found {
		t.Errorf("expected ModSecurity or generic WAF detection, got: %v", findings)
	}
}

// TestIncapsulaDetected: Imperva/Incapsula detected via cookie pattern.
func TestIncapsulaDetected(t *testing.T) {
	srv := incapsulaServer(t)
	defer srv.Close()

	m := wafscan.NewWithClient(clientFor(srv))
	findings, err := m.Run(context.Background(), module.Input{
		Target: srv.URL + "/",
	})
	if err != nil {
		t.Fatalf("Run failed: %v", err)
	}
	found := false
	for _, f := range findings {
		if strings.Contains(f.Extra["waf_name"], "Imperva") || strings.Contains(f.Extra["waf_name"], "generic") {
			found = true
		}
	}
	if !found {
		t.Errorf("expected Imperva/Incapsula detection, got: %v", findings)
	}
}

// TestF5BigIPDetected: F5 BIG-IP ASM detected via body.
func TestF5BigIPDetected(t *testing.T) {
	srv := f5BigIPServer(t)
	defer srv.Close()

	m := wafscan.NewWithClient(clientFor(srv))
	findings, err := m.Run(context.Background(), module.Input{
		Target: srv.URL + "/",
	})
	if err != nil {
		t.Fatalf("Run failed: %v", err)
	}
	if len(findings) == 0 {
		t.Error("expected F5 BIG-IP or generic WAF detection")
	}
}

// TestGenericBlock: generic WAF blocking (200 clean → 403 attack).
func TestGenericBlock(t *testing.T) {
	srv := genericBlockServer(t)
	defer srv.Close()

	m := wafscan.NewWithClient(clientFor(srv))
	findings, err := m.Run(context.Background(), module.Input{
		Target: srv.URL + "/",
	})
	if err != nil {
		t.Fatalf("Run failed: %v", err)
	}
	found := false
	for _, f := range findings {
		if f.Type == "waf_generic_block" || f.Type == "waf_detected" {
			found = true
		}
	}
	if !found {
		t.Errorf("expected generic_block finding, got: %v", findings)
	}
}

// TestNoWAF: clean server returns no WAF findings.
func TestNoWAF(t *testing.T) {
	srv := noWAFServer(t)
	defer srv.Close()

	m := wafscan.NewWithClient(clientFor(srv))
	findings, err := m.Run(context.Background(), module.Input{
		Target: srv.URL + "/",
	})
	if err != nil {
		t.Fatalf("Run failed: %v", err)
	}
	if len(findings) != 0 {
		t.Errorf("expected no findings on clean server, got %d: %v", len(findings), findings)
	}
}

// TestEmptyInput: no targets returns nil.
func TestEmptyInput(t *testing.T) {
	m := wafscan.New()
	findings, err := m.Run(context.Background(), module.Input{})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(findings) != 0 {
		t.Fatalf("expected empty findings, got %d", len(findings))
	}
}

// TestContextCancellation: cancelled context does not panic.
func TestContextCancellation(t *testing.T) {
	srv := cloudflareServer(t)
	defer srv.Close()

	ctx, cancel := context.WithCancel(context.Background())
	cancel()

	m := wafscan.NewWithClient(clientFor(srv))
	_, err := m.Run(ctx, module.Input{Target: srv.URL + "/"})
	_ = err
}

// TestDeduplication: same WAF on same URL not duplicated.
func TestDeduplication(t *testing.T) {
	srv := cloudflareServer(t)
	defer srv.Close()

	u := srv.URL + "/"
	m := wafscan.NewWithClient(clientFor(srv))
	findings, err := m.Run(context.Background(), module.Input{
		URLs: []string{u, u, u},
	})
	if err != nil {
		t.Fatalf("Run failed: %v", err)
	}
	seen := make(map[string]int)
	for _, f := range findings {
		key := f.URL + "|" + f.Type + "|" + f.Extra["waf_name"]
		seen[key]++
	}
	for k, count := range seen {
		if count > 1 {
			t.Errorf("duplicate finding %q count=%d", k, count)
		}
	}
}

// TestFindingFields: all required fields populated.
func TestFindingFields(t *testing.T) {
	srv := cloudflareServer(t)
	defer srv.Close()

	m := wafscan.NewWithClient(clientFor(srv))
	findings, err := m.Run(context.Background(), module.Input{
		Target: srv.URL + "/",
	})
	if err != nil {
		t.Fatalf("Run failed: %v", err)
	}
	if len(findings) == 0 {
		t.Fatal("expected at least one finding")
	}
	f := findings[0]
	if f.URL == "" {
		t.Error("URL empty")
	}
	if f.Detail == "" {
		t.Error("Detail empty")
	}
	if f.Severity == "" {
		t.Error("Severity empty")
	}
	if f.Extra["waf_name"] == "" {
		t.Error("Extra.waf_name empty")
	}
	if f.Extra["detection"] == "" {
		t.Error("Extra.detection empty")
	}
}

// TestFindingType: findings have expected type.
func TestFindingType(t *testing.T) {
	srv := cloudflareServer(t)
	defer srv.Close()

	m := wafscan.NewWithClient(clientFor(srv))
	findings, err := m.Run(context.Background(), module.Input{
		Target: srv.URL + "/",
	})
	if err != nil {
		t.Fatalf("Run failed: %v", err)
	}
	for _, f := range findings {
		if f.Type != "waf_detected" && f.Type != "waf_generic_block" {
			t.Errorf("unexpected finding.Type = %q", f.Type)
		}
	}
}

// TestParallelismOption: custom parallelism accepted.
func TestParallelismOption(t *testing.T) {
	srv := cloudflareServer(t)
	defer srv.Close()

	m := wafscan.NewWithClient(clientFor(srv))
	_, err := m.Run(context.Background(), module.Input{
		Target:  srv.URL + "/",
		Options: map[string]string{"parallelism": "3"},
	})
	if err != nil {
		t.Fatalf("Run failed: %v", err)
	}
}

// TestTargetFallback: input.Target used when URLs is empty.
func TestTargetFallback(t *testing.T) {
	srv := cloudflareServer(t)
	defer srv.Close()

	m := wafscan.NewWithClient(clientFor(srv))
	findings, err := m.Run(context.Background(), module.Input{
		Target: srv.URL + "/",
	})
	if err != nil {
		t.Fatalf("Run failed: %v", err)
	}
	if len(findings) == 0 {
		t.Fatal("expected findings from Target")
	}
}

// TestMultipleURLs: multiple targets processed.
func TestMultipleURLs(t *testing.T) {
	srv := cloudflareServer(t)
	defer srv.Close()

	m := wafscan.NewWithClient(clientFor(srv))
	_, err := m.Run(context.Background(), module.Input{
		URLs: []string{srv.URL + "/", srv.URL + "/api"},
	})
	if err != nil {
		t.Fatalf("Run failed: %v", err)
	}
}

// TestNewWithClient: does not panic.
func TestNewWithClient(t *testing.T) {
	c := &http.Client{Timeout: 1 * time.Second}
	m := wafscan.NewWithClient(c)
	if m == nil || m.Name() != "wafscan" {
		t.Fatal("NewWithClient failed")
	}
}

// TestNewWithSignatures: custom signatures override built-in.
func TestNewWithSignatures(t *testing.T) {
	customSig := wafscan.WAFSignature{
		Name:   "TestWAF",
		Vendor: "TestVendor",
		HeaderPatterns: map[string][]string{
			"x-test-waf": {"test-waf-value"},
		},
		Tags: []string{"test"},
	}

	srv := customSigServer(t, "x-test-waf", "test-waf-value-123")
	defer srv.Close()

	m := wafscan.NewWithSignatures([]wafscan.WAFSignature{customSig})
	m = wafscan.NewWithSignaturesAndClient([]wafscan.WAFSignature{customSig}, clientFor(srv))
	findings, err := m.Run(context.Background(), module.Input{
		Target: srv.URL + "/",
	})
	if err != nil {
		t.Fatalf("Run failed: %v", err)
	}
	found := false
	for _, f := range findings {
		if f.Extra["waf_name"] == "TestWAF" {
			found = true
		}
	}
	if !found {
		t.Errorf("expected TestWAF detection, got: %v", findings)
	}
}

// TestSeverityIsInfo: WAF detection findings are Info severity.
func TestSeverityIsInfo(t *testing.T) {
	srv := cloudflareServer(t)
	defer srv.Close()

	m := wafscan.NewWithClient(clientFor(srv))
	findings, err := m.Run(context.Background(), module.Input{
		Target: srv.URL + "/",
	})
	if err != nil {
		t.Fatalf("Run failed: %v", err)
	}
	for _, f := range findings {
		if f.Severity != module.SeverityInfo {
			t.Errorf("expected Info severity, got %q", f.Severity)
		}
	}
}

// TestGenericBlockNotDuplicatedWithSpecificWAF: if specific WAF detected, no generic block added.
func TestGenericBlockNotDuplicatedWithSpecificWAF(t *testing.T) {
	// Cloudflare server also triggers 403 on attack → could trigger both specific + generic.
	srv := cloudflareServer(t)
	defer srv.Close()

	m := wafscan.NewWithClient(clientFor(srv))
	findings, err := m.Run(context.Background(), module.Input{
		Target: srv.URL + "/",
	})
	if err != nil {
		t.Fatalf("Run failed: %v", err)
	}
	// When Cloudflare is identified, no generic block should be added.
	hasCloudflare := false
	hasGeneric := false
	for _, f := range findings {
		if f.Extra["waf_name"] == "Cloudflare" {
			hasCloudflare = true
		}
		if f.Type == "waf_generic_block" {
			hasGeneric = true
		}
	}
	if hasCloudflare && hasGeneric {
		t.Error("should not emit generic_block when specific WAF (Cloudflare) already detected")
	}
}

// TestDetailContainsWAFName: finding detail mentions WAF name.
func TestDetailContainsWAFName(t *testing.T) {
	srv := cloudflareServer(t)
	defer srv.Close()

	m := wafscan.NewWithClient(clientFor(srv))
	findings, err := m.Run(context.Background(), module.Input{
		Target: srv.URL + "/",
	})
	if err != nil {
		t.Fatalf("Run failed: %v", err)
	}
	for _, f := range findings {
		if f.Type == "waf_detected" && !strings.Contains(f.Detail, "[WAF]") {
			t.Errorf("Detail %q missing '[WAF]' prefix", f.Detail)
		}
	}
}

// TestTagsPopulated: findings include tags.
func TestTagsPopulated(t *testing.T) {
	srv := cloudflareServer(t)
	defer srv.Close()

	m := wafscan.NewWithClient(clientFor(srv))
	findings, err := m.Run(context.Background(), module.Input{
		Target: srv.URL + "/",
	})
	if err != nil {
		t.Fatalf("Run failed: %v", err)
	}
	for _, f := range findings {
		if f.Extra["tags"] == "" {
			t.Errorf("finding.Extra.tags empty for %v", f)
		}
	}
}
